### ISSUE TITLE
[Feature] set timezone for log

### ISSUE THREAD

**Issue by AntonioSun** [anasoid/docker-jmeter#59]
### Discussed in https://github.com/anasoid/docker-jmeter/discussions/58

<div type='discussions-op-text'>

<sup>Originally posted by **AntonioSun** January 21, 2022</sup>
Wish: able to set timezone so that logs can show correct local time:

![image](https://user-images.githubusercontent.com/2840074/150609596-560df691-f058-43a0-8e77-bb943a5d63c2.png)

E.g., `echo America/Toronto > /etc/timezone`

```
$ cat /etc/timezone 
America/Toronto
```

thx
</div>

**Comment by anasoid** [comment]
you can see how to change timezone in documentation : https://github.com/anasoid/docker-jmeter#timezone
